accepted = [
    "MIT",
    "ISC",
    "Unicode-3.0",
    "BSL-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "NCSA"
]

private = { ignore = true }
