[package]
name = "dac-player-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.59", features = [
    "Media_Control",
    "Foundation",
    "Foundation_Collections",
    "Storage_Streams"
] }
tokio = { version = "1.28", features = ["full"] }
async-trait = "0.1.68"
log = "0.4.25"
env_logger = "0.11.6"
eframe = "0.30.0"
futures = "0.3"
libc = "0.2.169"
objc2 = "0.6.0"
objc2-foundation = "0.3.0"
core-foundation-sys = "0.8.7"
block2 = "0.6.0"
dispatch2 = "0.2.0"

[[bin]]
name = "console"
path = "src/console.rs"

[[bin]]
name = "gui"
path = "src/main.rs"