[workspace]
resolver = "3"
members = ["core", "gui", "ports/macos", "ports/volumio", "ports/windows", "services/native"]

[workspace.package]
version = "0.2.0"
authors = ["Paweł Gorgoń", "HEM Sp. z o.o."]
description = "Tools supporting Ferrum Streaming Control Technology"

[workspace.dependencies]
async-trait = "0.1.88"
tokio = { version = "1.44", features = ["full"] }
futures = "0.3"
env_logger = "0.11"
fsct_core = { path = "core" }

#
#[dependencies]
#env_logger = "0.11.6"
#eframe = "0.30.0"
#fsct-core = { workspace = true, path = "core" }
#
#[target.'cfg(target_os = "windows")'.dependencies]
#fsct_windows_port = { workspace = true, path = "ports/windows" }
#
#[target.'cfg(target_os = "macos")'.dependencies]
#fsct_macos_port = { workspace = true, path = "ports/macos" }
#
#
#[[bin]]
#name = "fsct-native-service"
#path = "services/fsct_native_service.rs"

