[package]
name = "dac-player-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.59", features = [
    "Media_Control",
    "Foundation",
    "Foundation_Collections",
    "Storage_Streams"
] }
tokio = { version = "1.28", features = ["full"] }
async-trait = "0.1.68"
log = "0.4.25"
env_logger = "0.11.6"
eframe = "0.30.0"
futures = "0.3"
libc = "0.2.169"
nusb = "0.1.13"
uuid = { version = "1.16.0", features = ["v4"] }
bitflags = "2.8.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.0"
objc2-foundation = "0.3.0"
core-foundation-sys = "0.8.7"
block2 = "0.6.0"
dispatch2 = "0.2.0"

[[bin]]
name = "fsct-service"
path = "exec/fsct_service.rs"

[[bin]]
name = "console"
path = "testing/console.rs"

[[bin]]
name = "gui"
path = "testing/gui.rs"

[[bin]]
name = "test_bos_reading"
path = "testing/test_bos_reading.rs"

[[bin]]
name = "fsct_descriptor_dump"
path = "testing/fsct_descriptor_dump.rs"

[[bin]]
name = "requests_test"
path = "testing/requests_test.rs"

[[bin]]
name = "dfu_access_test"
path = "testing/test_dfu_access.rs"
