# fpm configuration for fsct-driver
--maintainer HEM R&D <rnd@hem-e.com>
--vendor HEM Sp. z o.o.
--license Apache-2.0
--category utils
--architecture native
--deb-user root
--deb-group root
--iteration 1
--description FSCT Host native driver service with systemd integration for Linux.
# don't create changelog automatically
# --deb-changelog is intentionally omitted; auto-changelog disabled
# scripts
--after-install ports/native/packages/linux/systemd/scripts/postinst
--before-remove ports/native/packages/linux/systemd/scripts/prerm
--after-remove ports/native/packages/linux/systemd/scripts/postrm
# deb specific
# systemd auto-enable handled by postinst; units are installed from staged tree
