[package]
name = "fsct-core"
description = "FSCT Host core library which includes usb definitions and communication of Ferrum Streaming Control Technology™ (FSCT). Additional licensing terms apply as described in LICENSE-FSCT.md. "
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true

[lib]
name = "fsct"

[dependencies]
uuid = { version = "1.17.0", features = ["v4", "v5"] }
bitflags = "2.8.0"
async-trait.workspace = true
anyhow.workspace = true

