[package]
name = "fsct_native_port"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
description = """FSCT Host native port which contains host OS bindings as well as service
executables of Ferrum Streaming Control Technology™ (FSCT) host implementation.
Additional licensing terms apply as described in LICENSE-FSCT.md."""

[dependencies]
fsct_core.workspace = true
tokio.workspace = true
async-trait.workspace = true
env_logger.workspace = true
anyhow.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.59", features = [
    "Media_Control",
    "Foundation",
    "Foundation_Collections",
    "Storage_Streams"
] }
windows-core = "0.59.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.0"
objc2-foundation = "0.3.0"
core-foundation-sys = "0.8.7"
block2 = "0.6.0"
dispatch2 = "0.2.0"
libc = "0.2.169"

[[bin]]
name = "fsct_native_service"
path = "src/service_main.rs"