[package]
name = "fsct_driver_service"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
description = """FSCT Host driver service with native player port. It contains host OS bindings as well as service
executables of Ferrum Streaming Control Technology™ (FSCT) host driver implementation.
Additional licensing terms apply as described in LICENSE-FSCT.md."""

[dependencies]
fsct_core.workspace = true
tokio.workspace = true
async-trait.workspace = true
env_logger.workspace = true
anyhow.workspace = true
log = "0.4"
log4rs = "1.2"
clap = { version = "4.5", features = ["derive"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.59", features = [
    "Media_Control",
    "Foundation",
    "Foundation_Collections",
    "Storage_Streams",
    "Win32_System_RemoteDesktop"
] }
windows-core = "0.59.0"
windows-service = "0.6.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.0"
objc2-foundation = "0.3.0"
core-foundation-sys = "0.8.7"
block2 = "0.6.0"
dispatch2 = "0.2.0"
libc = "0.2.169"

[[bin]]
name = "fsct_driver_service"
path = "src/service_main.rs"
