[package]
name = "fsct_windows_port"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
windows = { version = "0.59", features = [
    "Media_Control",
    "Foundation",
    "Foundation_Collections",
    "Storage_Streams"
] }
fsct_core.workspace = true
async-trait.workspace = true