[package]
name = "fsct-driver"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
description = """FSCT Host driver service with native player port. It contains host OS bindings as well as service
executables of Ferrum Streaming Control Technology™ (FSCT) host driver implementation.
Additional licensing terms apply as described in LICENSE-FSCT.md.

Ferrum Streaming Control Technology™ is a trademark of HEM Sp. z o.o.
"""

[dependencies]
fsct-core.workspace = true
tokio.workspace = true
async-trait.workspace = true
env_logger.workspace = true
anyhow.workspace = true
log = "0.4"
log4rs = "1.2"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio-util.workspace = true
uuid.workspace = true
fsct-client.workspace = true
serde_json.workspace = true
futures.workspace = true
nusb = { git = "https://github.com/HEM-RnD/nusb.git", tag = "v0.1.14-hem" }
bitflags = "2.8.0"
thiserror.workspace = true

[features]
test-utils = []

[[bin]]
name = "ipc_test_server"
path = "src/bin/ipc_test_server.rs"
required-features = ["test-utils"]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.3", features = [
    "Media_Control",
    "Foundation",
    "Foundation_Collections",
    "Storage_Streams",
    "Win32_System_RemoteDesktop",
] }
windows-core = "0.61.2"
windows-service = "0.8.0"
windows-future = "0.2.1"
winapi = { version = "0.3.9", features = ["winerror", "accctrl", "aclapi", "minwinbase", "securitybaseapi", "winbase", "winnt"] }

[target.'cfg(target_os = "macos")'.dependencies]
media-remote = { git = "https://github.com/HEM-RnD/media-remote.git", branch = "feature/add_playback_Rate" }
tokio = { workspace = true, features = ["rt"] }
raunch = "1.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
zbus = { version = "5.10.0", default-features = false, features = ["tokio"] }
futures-util = "0.3"
async-stream = "0.3"

[dev-dependencies]
nix = { version = "0.29", default-features = false, features = ["signal", "poll", "fs"] }
serde_json.workspace = true
tokio-util.workspace = true
