FROM debian:buster-slim

LABEL org.opencontainers.image.vendor="HEM Sp. z o.o."

RUN apt update && apt install --no-install-recommends -y curl ca-certificates gcc g++  && rm -rf \
    /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -Sf https://sh.rustup.rs -o /tmp/rustup-init.sh && chmod +x /tmp/rustup-init.sh && \
    /tmp/rustup-init.sh -y --default-toolchain 1.86.0 --profile minimal --target x86_64-unknown-linux-gnu && rm \
    /tmp/rustup-init.sh \
