FROM ghcr.io/${OWNER:-HEM-RnD}/fsct-cross:base-buster

LABEL org.opencontainers.image.vendor="HEM Sp. z o.o."

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc-aarch64-linux-gnu libc6-dev-arm64-cross \
  && rm -rf /var/lib/apt/lists/*

RUN rustup target add aarch64-unknown-linux-gnu
RUN mkdir -p /.cargo \
 && printf '[target.aarch64-unknown-linux-gnu]\nlinker = "aarch64-linux-gnu-gcc"\n' > /.cargo/config.toml