ARG OWNER
FROM ghcr.io/${OWNER:-hem-rnd}/fsct-cross:base-buster

LABEL org.opencontainers.image.vendor="HEM Sp. z o.o."

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc-arm-linux-gnueabihf libc6-dev-armhf-cross \
  && rm -rf /var/lib/apt/lists/*

RUN rustup target add armv7-unknown-linux-gnueabihf
RUN mkdir -p /.cargo \
 && printf '[target.armv7-unknown-linux-gnueabihf]\nlinker = "arm-linux-gnueabihf-gcc"\n' > /.cargo/config.toml