FROM debian:buster-slim

LABEL org.opencontainers.image.vendor="HEM Sp. z o.o."

RUN apt update && apt install --no-install-recommends -y curl ca-certificates gcc-aarch64-linux-gnu \
    libc6-dev-arm64-cross gcc g++ && rm -rf \
    /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -Sf https://sh.rustup.rs -o /tmp/rustup-init.sh && chmod +x /tmp/rustup-init.sh && \
    /tmp/rustup-init.sh -y --default-toolchain 1.86.0 --profile minimal --target aarch64-unknown-linux-gnu \
    && rm /tmp/rustup-init.sh

RUN mkdir -p /.cargo
RUN printf '[target.aarch64-unknown-linux-gnu]\n\
          linker = "aarch64-linux-gnu-gcc"' > /.cargo/config.toml