[package]
name = "fsct_macos_port"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
fsct_core.workspace = true
objc2 = "0.6.0"
objc2-foundation = "0.3.0"
core-foundation-sys = "0.8.7"
block2 = "0.6.0"
dispatch2 = "0.2.0"
libc = "0.2.169"
async-trait.workspace = true
futures.workspace = true
tokio.workspace = true